#!/usr/bin/env python
# coding: utf-8

# ## Even Fibonacci numbers
# Problem 2
# 

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# 
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

# In[ ]:


def Is_even(n):
    if n % 2 == 0:
        return True
    else:
        return False


# In[9]:


first = 1
second = 2

sum = 0

while (first < 4*10**6):
    if Is_even(first):
        sum = sum + first
    new = first + second
    first = second
    second = new 

print (sum)

